name: FastAPI Docker Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-docker:
    runs-on: runs-on: kat_testing

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t simple-test-app .

      - name: Run Container and Verify Output
        run: |
          # This runs the container. 
          # Because the Dockerfile uses CMD ["python", "main.py"],
          # the container will run the script and then EXIT immediately.
          docker run --name test-run-container simple-test-app
          # Cleanup
          docker rm test-run-container

      - name: Success Message
        run: echo "Pipeline completed successfully!"
